### ISSUE TITLE
Could not initialize class envs.config.GenericConfig

### ISSUE THREAD

**Issue by jungleblack007** [steineggerlab/ufcg#15]
I have intalled ufcg on WSL, however, when I used the same way (mamba install -y ufcg) to install it on ubuntu 22.04.2 LTS, it got wroing.
`ufcg -u
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class envs.config.GenericConfig
	at envs.toolkit.Prompt.print(Prompt.java:31)
	at pipeline.UFCGMainPipeline.main(UFCGMainPipeline.java:289)`
I checked my java is openjdk-17-jdk, how can I process it?

![image](https://user-images.githubusercontent.com/29190025/236862176-286231e9-57c0-455d-8486-33143a606dcf.png)

**Comment by endixk** [comment]
Hi, I tried to reproduce your error in both conda and docker environment, but both worked fine from my side.

Could you please try to create a clean conda environment and install the package again to see if the issue persists?

**Comment by JuliaPlewka** [comment]
Hi, I have the same error, also on Ubuntu systems, after installing it with mamba in clean conda envs. Do you have any solution?

**Comment by endixk** [comment]
Hey @JuliaPlewka, could you please run `java --version` and `which java` on the system from which you encountered the error? I suspect this occurs in specific version(s) of JDK/JRE.

**Comment by Muzixibeijin** [comment]
Hi, I have the same error, 

java -version
openjdk version "21.0.2-internal" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 21.0.2-internal-adhoc.conda.src, mixed mode, sharing)

which java
/home/zmz/miniconda3/envs/ufcg_env/bin/java
@endixk Do you have any solution?

**Comment by endixk** [comment]
@Muzixibeijin I recommend you to compile the program from source instead of using conda, as described in https://github.com/steineggerlab/ufcg?tab=readme-ov-file#build-from-source.

Alternatively, you can install older versions of JDK (8 or 11), which should work consistently.

I suppose the pre-compiled JAR included in conda package raises such exceptions in some environments. I will try to make it consistent in later versions.
