### ISSUE TITLE
Bugs on deleting temporary files

### ISSUE THREAD

**Issue by Changwanseo** [steineggerlab/ufcg#18]
* version 1.0.4 on Linux 20.04, conda build

* What I did

source ${PATH_ACTIVATE}/activate ufcg
for file in ${INPUT}/*.fna; 
do
    if [ ! -d "./tmp" ] 
    then
        mkdir ./tmp
    else
        rm -r ./tmp
        mkdir ./tmp
    fi
    cp ${INPUT}/${file##*/} ./tmp/${file##*/}
    ufcg profile -i ./tmp -o ./101_ufcg_profile -t ${THREAD} -v --developer --force 1
    
    rm -r ./tmp
done

* What happened
[JUN 08 15:57:13] UFCG  |:  AUGUSTUS is predicting genes... (contig chr14, position 444431-450895)
[JUN 08 15:57:13] DEBUG |:  exec: augustus --optCfgFile=/home/genome/anaconda3/envs/ufcg/share/ufcg-1.0.4-0/config/ppx.cfg --predictionStart=437264 --predictionEnd=457264 --proteinprofile=/home/genome/anaconda3/envs/ufcg/share/ufcg-1.0.4-0/config/model/pro/POL2.hmm /tmp/KMRB18080202/KMRB18080202_chr14.fna > /tmp/KMRB18080202/KMRB18080202_chr14_p447264_POL2.gff
[JUN 08 15:57:18] DEBUG |:  exec: head -1 /tmp/KMRB18080202/KMRB18080202_chr14_p447264_POL2.gff
[JUN 08 15:57:18] UFCG  |:  Parsing gene prediction result written on : /tmp/KMRB18080202/KMRB18080202_chr14_p447264_POL2.gff
[JUN 08 15:57:18] UFCG  |:  [Phase 3 : Validation]
[JUN 08 15:57:18] UFCG  |:  Exporting predicted genes to FASTA file : /tmp/KMRB18080202/KMRB18080202_POL2.fasta
[JUN 08 15:57:18] DEBUG |:  exec: mmseqs easy-search /tmp/KMRB18080202/KMRB18080202_POL2.fasta /home/genome/anaconda3/envs/ufcg/share/ufcg-1.0.4-0/config/seq/pro/POL2.fa /tmp/KMRB18080202/UFCG_b72a895b2b963217_POL2.fa.m8 /tmp/KMRB18080202/ --search-type 3 -e 0.001 --cov-mode 1 -c 0.8 --threads 1
[JUN 08 15:57:23] UFCG  |:  Extracting cDNA sequence of gene POL2...
[JUN 08 15:57:23] UFCG  |:  Query genome contains a single copy of gene POL2
[JUN 08 15:57:23] UFCG  |:  RESULT : [Single: 56 ; Duplicated: 5 ; Missing: 0]
[JUN 08 15:57:23] UFCG  |:  Writing results on : ./101_ufcg_profile/KMRB18080202.ucg
[JUN 08 15:57:23] UFCG  |:  Cleaning temporary files up...
[JUN 08 15:57:23] UFCG  |:  ERROR! java.util.ConcurrentModificationException: null
[JUN 08 15:57:23] UFCG  |:      at java.util.ArrayList$Itr.next(ArrayList.java:867)
[JUN 08 15:57:23] UFCG  |:      at envs.toolkit.FileStream.wipeOut(FileStream.java:101)
[JUN 08 15:57:23] UFCG  |:      at module.ProfileModule.run(ProfileModule.java:921)
[JUN 08 15:57:23] UFCG  |:      at pipeline.ModuleHandler.handle_profile(ModuleHandler.java:28)
[JUN 08 15:57:23] UFCG  |:      at pipeline.ModuleHandler.handle(ModuleHandler.java:66)
[JUN 08 15:57:23] UFCG  |:      at pipeline.UFCGMainPipeline.main(UFCGMainPipeline.java:281)

**Comment by endixk** [comment]
I never expected `ConcurrentModificataionException` to occur on that code block, since it couldn't be accessed by concurrent threads simultaneously. Does this happen consistently and/or frequently?
